//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProAgroAPIREST.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permisos
    {
        public int idPermiso { get; set; }
        public Nullable<int> idUsuario { get; set; }
        public Nullable<int> idEstado { get; set; }
    
        public virtual Estados Estados { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
